### ISSUE TITLE
Black Screen on open

### ISSUE THREAD

**Issue by skopplol** [coatlessali/UltraNix#14] opened 2024-03-19 21:55 UTC
I followed every step in the guide, but the game is just a black screen. Help? (MacOS 13.0)

**Comment by coatlessali** [comment] 2024-03-19 21:59
I'm not sure. Its really finnicky - it doesn't even work with 100% consistency on my own machine. Sometimes you have to run through the process more than once and I'm not sure why. You could try running it with the Mac version of BepInEx which seems to bypass some permissions issue.

**Comment by skopplol** [comment] 2024-03-19 22:01
i'll try that.

**Comment by skopplol** [comment] 2024-03-19 22:47
it sadly didnt work. Do i have to restart the WHOLE process?

**Comment by coatlessali** [comment] 2024-03-19 22:48
I'm honestly not sure.

**Comment by skopplol** [comment] 2024-03-19 23:04
here's an example vid (i went afk halfway through)

**Comment by skopplol** [comment] 2024-03-19 23:04
https://streamable.com/c9ukl5

**Comment by skopplol** [comment] 2024-03-19 23:47
tried reinstalling no dice

**Comment by coatlessali** [comment] 2024-04-16 14:38
Closing as can't reproduce as part of cleanup

**Closed by coatlessali** 2024-04-16 14:38 UTC
