### ISSUE TITLE
alt fire interupted by movement IF alt fire is mapped to keyboard key

### ISSUE THREAD

**Issue by zukigay** [coatlessali/UltraNix#13] opened 2024-02-04 13:10 UTC
because of ```There is a crippling mouse bug that causes any click/release input to repeat the last axis movement (including mouse movement and scroll wheel) by one unit. This means if you scroll to change weapons and don't move the mouse before clicking, you will change weapons again upon trying to fire.``` i mapped m1 and m2 on my mouse to j and k respectively to work around it and because of this i found a new ultranix exclusive bug.

The bug is that if alt fire mapped to a keyboard key and you press/left go of a movement button it will interrupt the alt fire action so if your holding a charge on the pistol you will fire as soon as you press one/or let go of w/a/s/d.

**Comment by coatlessali** [comment] 2024-02-04 16:14
Is this on Mac or Linux? Also, could you do me a favor and try the left/right arrow keys?

**Comment by zooki2006** [comment] 2024-02-04 17:55
> Is this on Mac or Linux? Also, could you do me a favor and try the left/right arrow keys?
1.linux
2. i just relised any key will cancel a alt fire hold

**Comment by coatlessali** [comment] 2024-02-04 17:56
Is this X11 or Wayland?

**Comment by zooki2006** [comment] 2024-02-04 17:56
X11

**Comment by coatlessali** [comment] 2024-02-04 17:57
Try running the game in gamescope if possible, and see if it persists. I'll try to reproduce this in a bit.

**Comment by zooki2006** [comment] 2024-02-04 17:59
Sadly I have never been able to get gamescope working on my system, I assume it's due to my nvidia card.

**Comment by coatlessali** [comment] 2024-02-04 18:03
The latest proprietary drivers should support it. I'm getting on to try to reproduce this.

**Comment by coatlessali** [comment] 2024-02-04 18:08
I can't seem to reproduce this on Xwayland.

**Comment by zooki2006** [comment] 2024-02-04 18:32
Tried testing gamescope with glxgears and it just showed a black window that was stealing my mouse, and wouldn't close without sending a "kill -kill pid" command.
zuki ~ > gamescope glxgears
vblank: Using timerfd.
No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.
wlserver: [backend/headless/backend.c:67] Creating headless backend
vulkan: selecting physical device 'NVIDIA GeForce RTX 3060 Ti': queue family 2 (general queue family 0)
vulkan: physical device supports DRM format modifiers
vulkan: vkGetPhysicalDeviceFormatProperties2 returned zero modifiers for DRM format 0x3231564E (VkResult: 0)
vulkan: vkGetPhysicalDeviceFormatProperties2 returned zero modifiers for DRM format 0x38344241 (VkResult: 0)
vulkan: vkGetPhysicalDeviceFormatProperties2 returned zero modifiers for DRM format 0x38344258 (VkResult: 0)
vulkan: supported DRM formats for sampling usage:
vulkan:   AR24 (0x34325241)
vulkan:   XR24 (0x34325258)
vulkan:   AB24 (0x34324241)
vulkan:   XB24 (0x34324258)
vulkan:   RG16 (0x36314752)
vulkan:   AB4H (0x48344241)
vulkan:   XB4H (0x48344258)
vulkan:   AB30 (0x30334241)
vulkan:   XB30 (0x30334258)
vulkan:   AR30 (0x30335241)
vulkan:   XR30 (0x30335258)
vulkan: Creating Gamescope nested swapchain with format 44 and colorspace 0
wlserver: [wayland] unable to lock lockfile /run/user/1000/gamescope-0.lock, maybe another compositor is running
wlserver: Running compositor on wayland display 'gamescope-1'
wlserver: [backend/headless/backend.c:17] Starting headless backend
wlserver: [xwayland/server.c:108] Starting Xwayland on :2
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Could not resolve keysym XF86CameraAccessEnable
> Warning:          Could not resolve keysym XF86CameraAccessDisable
> Warning:          Could not resolve keysym XF86CameraAccessToggle
> Warning:          Could not resolve keysym XF86NextElement
> Warning:          Could not resolve keysym XF86PreviousElement
> Warning:          Could not resolve keysym XF86AutopilotEngageToggle
> Warning:          Could not resolve keysym XF86MarkWaypoint
> Warning:          Could not resolve keysym XF86Sos
> Warning:          Could not resolve keysym XF86NavChart
> Warning:          Could not resolve keysym XF86FishingChart
> Warning:          Could not resolve keysym XF86SingleRangeRadar
> Warning:          Could not resolve keysym XF86DualRangeRadar
> Warning:          Could not resolve keysym XF86RadarOverlay
> Warning:          Could not resolve keysym XF86TraditionalSonar
> Warning:          Could not resolve keysym XF86ClearvuSonar
> Warning:          Could not resolve keysym XF86SidevuSonar
> Warning:          Could not resolve keysym XF86NavInfo
Errors from xkbcomp are not fatal to the X server
wlserver: [types/wlr_compositor.c:692] New wlr_surface 0x5cbc2c98d130 (res 0x5cbc2c4aef10)
wlserver: [xwayland/server.c:273] Xserver is ready
pipewire: stream state changed: connecting
pipewire: stream state changed: paused
pipewire: stream available on node ID: 126
vulkan: Creating Gamescope nested swapchain with format 44 and colors
pace 0
pipewire: renegotiating stream params (size: 1280x720)
wlserver: [types/wlr_compositor.c:692] New wlr_surface 0x5cbc2c930d70 (res 0x5cbc2cb310c0)
xwm: got the same buffer committed twice, ignoring.
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Unsupported maximum keycode 708, clipping.
>                   X11 cannot support keycodes above 255.
> Warning:          Could not resolve keysym XF86CameraAccessEnable
> Warning:          Could not resolve keysym XF86CameraAccessDisable
> Warning:          Could not resolve keysym XF86CameraAccessToggle
> Warning:          Could not resolve keysym XF86NextElement
> Warning:          Could not resolve keysym XF86PreviousElement
> Warning:          Could not resolve keysym XF86AutopilotEngageToggle
> Warning:          Could not resolve keysym XF86MarkWaypoint
> Warning:          Could not resolve keysym XF86Sos
> Warning:          Could not resolve keysym XF86NavChart
> Warning:          Could not resolve keysym XF86FishingChart
> Warning:          Could not resolve keysym XF86SingleRangeRadar
> Warning:          Could not resolve keysym XF86DualRangeRadar
> Warning:          Could not resolve keysym XF86RadarOverlay
> Warning:          Could not resolve keysym XF86TraditionalSonar
> Warning:          Could not resolve keysym XF86ClearvuSonar
> Warning:          Could not resolve keysym XF86SidevuSonar
> Warning:          Could not resolve keysym XF86NavInfo
Errors from xkbcomp are not fatal to the X server
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
^Cgamescope: Received Interrupt signal, forwarding to child!
gamescope: Received Interrupt signal, attempting shutdown!
gamescope: children shut down!
xwm: X11 I/O error
zsh: killed     gamescope glxgears

**Comment by coatlessali** [comment] 2024-02-04 18:34
Interesting. What keyboard/mouse do you have btw?

**Comment by zooki2006** [comment] 2024-02-04 21:49
a Logitech G203 LIGHTSYNC Gaming Mouse
and a mechanical keyboard, i got as a gift a few years ago the brand is "EalgeTec"   with "P/N: ET-KGO40-RGB-UK" written on it.

**Comment by zooki2006** [comment] 2024-02-06 09:04
also gamescope will crash even if i have no keyboard plugged in.

**Comment by coatlessali** [comment] 2024-10-27 02:43
cannot reproduce

**Closed by coatlessali** 2024-10-27 02:43 UTC
Labels: bug, Linux
